language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: aRPxHbxzev1bxAQrD+U6vopacJoz80JcJXCElAi/9dP9M63ho3BIGe99CUkpNmVepLZnMyUPucJSUXg2WIFb/NM3lbLJ06xdPnB8y6/CVClsyptXFR1jNqEBZ+mfUPk35qD0YRryXKH2gMH3gLhKsmzzhUxTBZ7YCl6BEU/rBrs=
  app: spatula-site
  on:
    repo: KitchnSink/Project-Spatula
    branch: master
    rvm: 2.0.0
  run:
  - "bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment"
  - "rake db:migrate"
  - restart
before_script:
- psql -c 'create database spatula_test' -U postgres
- rake db:migrate
env:
- DB=postgresql
